### ISSUE TITLE
is overlapped arg in findall working?

### ISSUE THREAD

**Issue by pedromoraesh** [mrabarnett/mrab-regex#458]
Hi, I'm trying to extract overlapping words inside a text, but the first match ignores the others?

```python
import regex

list_of_words = ["good", "there", "good to have", "go"]
prhase = ["there is the car i needed", "good to have options"]

for snippet in snippets:
     finds = regex.findall('|'.join(list_of_words), prhase, overlapped=True)
```

I also tried a pattern

```python
pattern = r'(\W|^)(' + '|'.join([f'{k}' for k in list_of_words]) + ')(\W|$)'
```

But both cases always show only "good" and "there".

The result should be:
```python
["there"]
["good", "good to have"]
```

If my problem is not related to the issues, feel free to close without answering.

**Comment by mrabarnett** [comment]
What you're missing is that alternatives are always checked in the order that they're listed, so:

   good|there|good to have|go

checks for 'good' first, and only if it subsequently fails to match does it retry and check for 'there', then 'good to have', etc.

You need to sort the alternatives to cope with that:

   good to have|good|there|go

The regex module provides a way to do that using `\L<name>`:

    regex.findall(r'\L<words>', snipped, words=list_of_words)

The `overlapped` control is for when you want to find overlapping matches:

    regex.findall(r'big dog|dog', 'a big dog', overlapped=True)

It looks for the next match from just after where the previous match started instead of from where the previous match ended, so it found 'big dog', then searched from the 'i' for the next match, which is 'dog'.

**Comment by pedromoraesh** [comment]
Thanks, @mrabarnett . I did try your solution, but no way to work even if I change my sequence or code. The match needs to restart at the exact start of the previous match.

I need to match 800K Words x 132M Sentences but the overlapping is slowing me down :/

Btw thanks for the answer!

**Comment by mrabarnett** [comment]
If the string contains 'good to have' then it also contains 'good' because 'good' is a substring of 'good to have', so if `.findall` returns ['good to have'] you can add 'good' to the list.
