### ISSUE TITLE
Default value for `allcaptures`, `capturesdict` when no matches?

### ISSUE THREAD

**Issue by failable** [mrabarnett/mrab-regex#537]
For groups, both have `None` for `?` when no matches.

```
>>> re.match(r"(?P<word>\w+) (?P<digits>\d+)?\n", "one \n").groups()
('one', None)
>>> regex.match(r"(?P<word>\w+) (?P<digits>\d+)?\n", "one \n").groups()
('one', None)
```

For `allcaptures`,

```
>>> regex.match(r"(?:(?P<word>\w+) (?P<digits>\d+)?\n)+", "one \ntwo 2\n").allcaptures()
(['one \ntwo 2\n'], ['one', 'two'], ['2'])
>>> regex.match(r"(?:(?P<word>\w+) (?P<digits>\d+)?\n)+", "one 1\ntwo \n").allcaptures()
(['one 1\ntwo \n'], ['one', 'two'], ['1'])
```

but I expected the result would be

```
>>> regex.match(r"(?:(?P<word>\w+) (?P<digits>\d+)?\n)+", "one \ntwo 2\n").allcaptures()
(['one \ntwo 2\n'], ['one', 'two'], [None, '2'])
>>> regex.match(r"(?:(?P<word>\w+) (?P<digits>\d+)?\n)+", "one 1\ntwo \n").allcaptures()
(['one 1\ntwo \n'], ['one', 'two'], ['1', None])
```

The same happens for `capturesdict`

```
>>> regex.match(r"(?:(?P<word>\w+) (?P<digits>\d+)?\n)+", "one 1\ntwo \n").capturesdict()
{'word': ['one', 'two'], 'digits': ['1']}
>>> regex.match(r"(?:(?P<word>\w+) (?P<digits>\d+)?\n)+", "one \ntwo 2\n").capturesdict()
{'word': ['one', 'two'], 'digits': ['2']}
```

Because the subsequent handling of repeated groups is often likely to be done in this way,

```
d = ....capturesdict()
for word, digit in zip(d["word"], d["digits"], strict=True):
    ....
```

 in such cases it's not possible to match the groups with each other. Would it better to have `None` values for non matches?

**Comment by mrabarnett** [comment]
It remembers matches, not non-matches. The only reason that `.groups` can contain `None` is that it returns a tuple of the entire match plus the last match of each group, so if a group hasn't matched *at all*, it needs some kind of default value to indicate that.

Putting `(?:...)+` around a pattern is not the same as repeating `.match` because it can occur within subpattern. For simple patterns such as these, remembering non-matches can seem an obvious thing to do, but when you have patterns with repeats within repeats and non-matches within them, it soon becomes clear that it's not the right thing to do.
